//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//
//     Zmiany w tym pliku mogą spowodować niewłaściwe zachowanie i zostaną utracone
//     w przypadku ponownego wygenerowania kodu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JavaEventService
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://rsiprojekt.example.com/", ConfigurationName="JavaEventService.EventService")]
    public interface EventService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://rsiprojekt.example.com/EventService/getAllEventsRequest", ReplyAction="http://rsiprojekt.example.com/EventService/getAllEventsResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<JavaEventService.getAllEventsResponse> getAllEventsAsync(JavaEventService.getAllEventsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://rsiprojekt.example.com/EventService/getEventByIdRequest", ReplyAction="http://rsiprojekt.example.com/EventService/getEventByIdResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<JavaEventService.getEventByIdResponse> getEventByIdAsync(JavaEventService.getEventByIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://rsiprojekt.example.com/EventService/getEventsByNameRequest", ReplyAction="http://rsiprojekt.example.com/EventService/getEventsByNameResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<JavaEventService.getEventsByNameResponse> getEventsByNameAsync(JavaEventService.getEventsByNameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://rsiprojekt.example.com/EventService/getEventsForDayRequest", ReplyAction="http://rsiprojekt.example.com/EventService/getEventsForDayResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<JavaEventService.getEventsForDayResponse> getEventsForDayAsync(JavaEventService.getEventsForDayRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://rsiprojekt.example.com/EventService/getEventsForWeekRequest", ReplyAction="http://rsiprojekt.example.com/EventService/getEventsForWeekResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<JavaEventService.getEventsForWeekResponse> getEventsForWeekAsync(JavaEventService.getEventsForWeekRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://rsiprojekt.example.com/EventService/getEventsForMonthRequest", ReplyAction="http://rsiprojekt.example.com/EventService/getEventsForMonthResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<JavaEventService.getEventsForMonthResponse> getEventsForMonthAsync(JavaEventService.getEventsForMonthRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://rsiprojekt.example.com/EventService/updateEventRequest", ReplyAction="http://rsiprojekt.example.com/EventService/updateEventResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<JavaEventService.updateEventResponse> updateEventAsync(JavaEventService.updateEventRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://rsiprojekt.example.com/EventService/deleteEventRequest", ReplyAction="http://rsiprojekt.example.com/EventService/deleteEventResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<JavaEventService.deleteEventResponse> deleteEventAsync(JavaEventService.deleteEventRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://rsiprojekt.example.com/EventService/getEventsAsPDFRequest", ReplyAction="http://rsiprojekt.example.com/EventService/getEventsAsPDFResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<JavaEventService.getEventsAsPDFResponse> getEventsAsPDFAsync(JavaEventService.getEventsAsPDFRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://rsiprojekt.example.com/EventService/addEventRequest", ReplyAction="http://rsiprojekt.example.com/EventService/addEventResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<JavaEventService.addEventResponse> addEventAsync(JavaEventService.addEventRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rsiprojekt.example.com/")]
    public partial class @event
    {
        
        private string idField;
        
        private string nameField;
        
        private string typeField;
        
        private string dateField;
        
        private int weekField;
        
        private int monthField;
        
        private int yearField;
        
        private string descriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string date
        {
            get
            {
                return this.dateField;
            }
            set
            {
                this.dateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int week
        {
            get
            {
                return this.weekField;
            }
            set
            {
                this.weekField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int month
        {
            get
            {
                return this.monthField;
            }
            set
            {
                this.monthField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public int year
        {
            get
            {
                return this.yearField;
            }
            set
            {
                this.yearField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAllEvents", WrapperNamespace="http://rsiprojekt.example.com/", IsWrapped=true)]
    public partial class getAllEventsRequest
    {
        
        public getAllEventsRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAllEventsResponse", WrapperNamespace="http://rsiprojekt.example.com/", IsWrapped=true)]
    public partial class getAllEventsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://rsiprojekt.example.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public JavaEventService.@event[] @return;
        
        public getAllEventsResponse()
        {
        }
        
        public getAllEventsResponse(JavaEventService.@event[] @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getEventById", WrapperNamespace="http://rsiprojekt.example.com/", IsWrapped=true)]
    public partial class getEventByIdRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://rsiprojekt.example.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        public getEventByIdRequest()
        {
        }
        
        public getEventByIdRequest(string arg0)
        {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getEventByIdResponse", WrapperNamespace="http://rsiprojekt.example.com/", IsWrapped=true)]
    public partial class getEventByIdResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://rsiprojekt.example.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public JavaEventService.@event @return;
        
        public getEventByIdResponse()
        {
        }
        
        public getEventByIdResponse(JavaEventService.@event @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getEventsByName", WrapperNamespace="http://rsiprojekt.example.com/", IsWrapped=true)]
    public partial class getEventsByNameRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://rsiprojekt.example.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        public getEventsByNameRequest()
        {
        }
        
        public getEventsByNameRequest(string arg0)
        {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getEventsByNameResponse", WrapperNamespace="http://rsiprojekt.example.com/", IsWrapped=true)]
    public partial class getEventsByNameResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://rsiprojekt.example.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public JavaEventService.@event[] @return;
        
        public getEventsByNameResponse()
        {
        }
        
        public getEventsByNameResponse(JavaEventService.@event[] @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getEventsForDay", WrapperNamespace="http://rsiprojekt.example.com/", IsWrapped=true)]
    public partial class getEventsForDayRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://rsiprojekt.example.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        public getEventsForDayRequest()
        {
        }
        
        public getEventsForDayRequest(string arg0)
        {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getEventsForDayResponse", WrapperNamespace="http://rsiprojekt.example.com/", IsWrapped=true)]
    public partial class getEventsForDayResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://rsiprojekt.example.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public JavaEventService.@event[] @return;
        
        public getEventsForDayResponse()
        {
        }
        
        public getEventsForDayResponse(JavaEventService.@event[] @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getEventsForWeek", WrapperNamespace="http://rsiprojekt.example.com/", IsWrapped=true)]
    public partial class getEventsForWeekRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://rsiprojekt.example.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://rsiprojekt.example.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg1;
        
        public getEventsForWeekRequest()
        {
        }
        
        public getEventsForWeekRequest(int arg0, int arg1)
        {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getEventsForWeekResponse", WrapperNamespace="http://rsiprojekt.example.com/", IsWrapped=true)]
    public partial class getEventsForWeekResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://rsiprojekt.example.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public JavaEventService.@event[] @return;
        
        public getEventsForWeekResponse()
        {
        }
        
        public getEventsForWeekResponse(JavaEventService.@event[] @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getEventsForMonth", WrapperNamespace="http://rsiprojekt.example.com/", IsWrapped=true)]
    public partial class getEventsForMonthRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://rsiprojekt.example.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://rsiprojekt.example.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg1;
        
        public getEventsForMonthRequest()
        {
        }
        
        public getEventsForMonthRequest(int arg0, int arg1)
        {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getEventsForMonthResponse", WrapperNamespace="http://rsiprojekt.example.com/", IsWrapped=true)]
    public partial class getEventsForMonthResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://rsiprojekt.example.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public JavaEventService.@event[] @return;
        
        public getEventsForMonthResponse()
        {
        }
        
        public getEventsForMonthResponse(JavaEventService.@event[] @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="updateEvent", WrapperNamespace="http://rsiprojekt.example.com/", IsWrapped=true)]
    public partial class updateEventRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://rsiprojekt.example.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public JavaEventService.@event arg0;
        
        public updateEventRequest()
        {
        }
        
        public updateEventRequest(JavaEventService.@event arg0)
        {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="updateEventResponse", WrapperNamespace="http://rsiprojekt.example.com/", IsWrapped=true)]
    public partial class updateEventResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://rsiprojekt.example.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public updateEventResponse()
        {
        }
        
        public updateEventResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="deleteEvent", WrapperNamespace="http://rsiprojekt.example.com/", IsWrapped=true)]
    public partial class deleteEventRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://rsiprojekt.example.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        public deleteEventRequest()
        {
        }
        
        public deleteEventRequest(string arg0)
        {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="deleteEventResponse", WrapperNamespace="http://rsiprojekt.example.com/", IsWrapped=true)]
    public partial class deleteEventResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://rsiprojekt.example.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public deleteEventResponse()
        {
        }
        
        public deleteEventResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getEventsAsPDF", WrapperNamespace="http://rsiprojekt.example.com/", IsWrapped=true)]
    public partial class getEventsAsPDFRequest
    {
        
        public getEventsAsPDFRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getEventsAsPDFResponse", WrapperNamespace="http://rsiprojekt.example.com/", IsWrapped=true)]
    public partial class getEventsAsPDFResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://rsiprojekt.example.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary")]
        public byte[] @return;
        
        public getEventsAsPDFResponse()
        {
        }
        
        public getEventsAsPDFResponse(byte[] @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="addEvent", WrapperNamespace="http://rsiprojekt.example.com/", IsWrapped=true)]
    public partial class addEventRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://rsiprojekt.example.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public JavaEventService.@event arg0;
        
        public addEventRequest()
        {
        }
        
        public addEventRequest(JavaEventService.@event arg0)
        {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="addEventResponse", WrapperNamespace="http://rsiprojekt.example.com/", IsWrapped=true)]
    public partial class addEventResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://rsiprojekt.example.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public addEventResponse()
        {
        }
        
        public addEventResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface EventServiceChannel : JavaEventService.EventService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class EventServiceClient : System.ServiceModel.ClientBase<JavaEventService.EventService>, JavaEventService.EventService
    {
        
        /// <summary>
        /// Wdróż tę metodę częściową, aby skonfigurować punkt końcowy usługi.
        /// </summary>
        /// <param name="serviceEndpoint">Punkt końcowy do skonfigurowania</param>
        /// <param name="clientCredentials">Poświadczenia klienta</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public EventServiceClient() : 
                base(EventServiceClient.GetDefaultBinding(), EventServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.EventServicePort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public EventServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(EventServiceClient.GetBindingForEndpoint(endpointConfiguration), EventServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public EventServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(EventServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public EventServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(EventServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public EventServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<JavaEventService.getAllEventsResponse> JavaEventService.EventService.getAllEventsAsync(JavaEventService.getAllEventsRequest request)
        {
            return base.Channel.getAllEventsAsync(request);
        }
        
        public System.Threading.Tasks.Task<JavaEventService.getAllEventsResponse> getAllEventsAsync()
        {
            JavaEventService.getAllEventsRequest inValue = new JavaEventService.getAllEventsRequest();
            return ((JavaEventService.EventService)(this)).getAllEventsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<JavaEventService.getEventByIdResponse> JavaEventService.EventService.getEventByIdAsync(JavaEventService.getEventByIdRequest request)
        {
            return base.Channel.getEventByIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<JavaEventService.getEventByIdResponse> getEventByIdAsync(string arg0)
        {
            JavaEventService.getEventByIdRequest inValue = new JavaEventService.getEventByIdRequest();
            inValue.arg0 = arg0;
            return ((JavaEventService.EventService)(this)).getEventByIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<JavaEventService.getEventsByNameResponse> JavaEventService.EventService.getEventsByNameAsync(JavaEventService.getEventsByNameRequest request)
        {
            return base.Channel.getEventsByNameAsync(request);
        }
        
        public System.Threading.Tasks.Task<JavaEventService.getEventsByNameResponse> getEventsByNameAsync(string arg0)
        {
            JavaEventService.getEventsByNameRequest inValue = new JavaEventService.getEventsByNameRequest();
            inValue.arg0 = arg0;
            return ((JavaEventService.EventService)(this)).getEventsByNameAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<JavaEventService.getEventsForDayResponse> JavaEventService.EventService.getEventsForDayAsync(JavaEventService.getEventsForDayRequest request)
        {
            return base.Channel.getEventsForDayAsync(request);
        }
        
        public System.Threading.Tasks.Task<JavaEventService.getEventsForDayResponse> getEventsForDayAsync(string arg0)
        {
            JavaEventService.getEventsForDayRequest inValue = new JavaEventService.getEventsForDayRequest();
            inValue.arg0 = arg0;
            return ((JavaEventService.EventService)(this)).getEventsForDayAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<JavaEventService.getEventsForWeekResponse> JavaEventService.EventService.getEventsForWeekAsync(JavaEventService.getEventsForWeekRequest request)
        {
            return base.Channel.getEventsForWeekAsync(request);
        }
        
        public System.Threading.Tasks.Task<JavaEventService.getEventsForWeekResponse> getEventsForWeekAsync(int arg0, int arg1)
        {
            JavaEventService.getEventsForWeekRequest inValue = new JavaEventService.getEventsForWeekRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            return ((JavaEventService.EventService)(this)).getEventsForWeekAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<JavaEventService.getEventsForMonthResponse> JavaEventService.EventService.getEventsForMonthAsync(JavaEventService.getEventsForMonthRequest request)
        {
            return base.Channel.getEventsForMonthAsync(request);
        }
        
        public System.Threading.Tasks.Task<JavaEventService.getEventsForMonthResponse> getEventsForMonthAsync(int arg0, int arg1)
        {
            JavaEventService.getEventsForMonthRequest inValue = new JavaEventService.getEventsForMonthRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            return ((JavaEventService.EventService)(this)).getEventsForMonthAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<JavaEventService.updateEventResponse> JavaEventService.EventService.updateEventAsync(JavaEventService.updateEventRequest request)
        {
            return base.Channel.updateEventAsync(request);
        }
        
        public System.Threading.Tasks.Task<JavaEventService.updateEventResponse> updateEventAsync(JavaEventService.@event arg0)
        {
            JavaEventService.updateEventRequest inValue = new JavaEventService.updateEventRequest();
            inValue.arg0 = arg0;
            return ((JavaEventService.EventService)(this)).updateEventAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<JavaEventService.deleteEventResponse> JavaEventService.EventService.deleteEventAsync(JavaEventService.deleteEventRequest request)
        {
            return base.Channel.deleteEventAsync(request);
        }
        
        public System.Threading.Tasks.Task<JavaEventService.deleteEventResponse> deleteEventAsync(string arg0)
        {
            JavaEventService.deleteEventRequest inValue = new JavaEventService.deleteEventRequest();
            inValue.arg0 = arg0;
            return ((JavaEventService.EventService)(this)).deleteEventAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<JavaEventService.getEventsAsPDFResponse> JavaEventService.EventService.getEventsAsPDFAsync(JavaEventService.getEventsAsPDFRequest request)
        {
            return base.Channel.getEventsAsPDFAsync(request);
        }
        
        public System.Threading.Tasks.Task<JavaEventService.getEventsAsPDFResponse> getEventsAsPDFAsync()
        {
            JavaEventService.getEventsAsPDFRequest inValue = new JavaEventService.getEventsAsPDFRequest();
            return ((JavaEventService.EventService)(this)).getEventsAsPDFAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<JavaEventService.addEventResponse> JavaEventService.EventService.addEventAsync(JavaEventService.addEventRequest request)
        {
            return base.Channel.addEventAsync(request);
        }
        
        public System.Threading.Tasks.Task<JavaEventService.addEventResponse> addEventAsync(JavaEventService.@event arg0)
        {
            JavaEventService.addEventRequest inValue = new JavaEventService.addEventRequest();
            inValue.arg0 = arg0;
            return ((JavaEventService.EventService)(this)).addEventAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.EventServicePort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.MessageEncoding = System.ServiceModel.WSMessageEncoding.Mtom;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Nie można znaleźć punktu końcowego o nazwie „{0}”.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.EventServicePort))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:8080/RSIProjekt_war_exploded/eventService");
            }
            throw new System.InvalidOperationException(string.Format("Nie można znaleźć punktu końcowego o nazwie „{0}”.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return EventServiceClient.GetBindingForEndpoint(EndpointConfiguration.EventServicePort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return EventServiceClient.GetEndpointAddress(EndpointConfiguration.EventServicePort);
        }
        
        public enum EndpointConfiguration
        {
            
            EventServicePort,
        }
    }
}
